### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by kylewr** [SavoryApple/MongoDB-Express-React-Node-full-stack-app-with-CRUD#1]

**Comment by SavoryApple** [comment]
Hi ruff

**Comment by kylewr** [comment]
hi sap
also its been 7 months dawg 😭

**Comment by SavoryApple** [comment]
Yoyoyoyoyyoyo ruffr

**Comment by kylewr** [comment]
real!

**Comment by SavoryApple** [comment]
The one and on-

**Comment by kylewr** [comment]
hehehe!!! what is this repeo for

**Comment by SavoryApple** [comment]
Hehehehehehjust an example of a basic website using express servers, react
front end, mongo database blah blah blah with crud

**Comment by kylewr** [comment]
oh i see
im going to close this issue now cuz i dont feel like it should be open hehehaw!!! have fuen

**Comment by kylewr** [comment]
meow what does this button do

**Comment by SavoryApple** [comment]
Cool
